site_name: 'Revit'
docs_dir: '../../docs/pt'
site_dir: '../../generated/pt'

theme:
    name: material
    custom_dir: '../../overrides/'
    logo: assets/images/logo.svg
    favicon: assets/images/favicon.ico
    language: pt

# extra_css:
#   - assets/stylesheets/yesplan.css

extra:
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Portugues
    - name: Portugues
      link: /pt/
      lang: pt


plugins:
  - search:                                         
      lang: pt

nav:
- Welcome: index.md
