services:
  revit-back:
    container_name: revit-back
    build:
      context: .
      dockerfile: DockerfileBack
    working_dir: /code
    volumes:
      - ./back/src:/code/src
      - ./back/docs/requirements.txt:/code/requirements.txt
    ports:
      - "8080:8080"
    environment:
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
      - FASTAPI_APP=${FASTAPI_APP}
      - FASTAPI_HOST=${FASTAPI_HOST}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - FASTAPI_LOG_LEVEL=${FASTAPI_LOG_LEVEL}
      - FASTAPI_RELOAD=${FASTAPI_RELOAD}
      - FASTAPI_WORKERS=${FASTAPI_WORKERS}
    command: python /code/src/main.py

  revit-front:
    container_name: revit-front
    build:
      context: ./front/revit
      dockerfile: DockerfileFront
    ports:
      - "3000:3000"
    volumes:
      - ./front/revit:/app
      - /app/node_modules
    command: npm start
